[package]
name = "edge-api"
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
application.workspace = true

anyhow.workspace = true

axum.workspace = true
tokio.workspace = true

sea-orm.workspace = true
